/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Genericos;

import java.util.ArrayList;
import javafx.scene.control.RadioButton;
import javax.swing.*;

/**
 *
 * @author T-101
 */
public class VentanaCuestionario extends javax.swing.JPanel {
JButton
    /**
     * Creates new form VentanaCuestionario
     */
    public VentanaCuestionario() {
        initComponents();
        GeneradorCuestionario generador = new GeneradorCuestionario();
        
        JLabel l1=new JLabel();
        
        ArrayList<JRadioButton> radios=new ArrayList();
        
        for (Pregunta p : generador.getCuestionario().getPreguntas()) {
           // System.out.println(p.getTitulo());
           l1.setText(p.getTitulo());
           jPanel1.add(l1);
           
           ButtonGroup grupo=new ButtonGroup();
           
            for (Opcion o : p.getOpciones()) {
                //System.out.println(o.getTitulo() + " " + o.isCorrecta());
                JRadioButton r=new JRadioButton();
                r.setText(o.getTitulo());
                grupo.add(r);
                jPanel1.add(r);
            }
            
            boton=new JButton("Checar respuesta");
            jPanel1.add(boton);
        }
        boton.addActionListener(evento->{
        JOptionPane.showConfirmDialog(this, "Correcto");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 102));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
