/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Opcion;
import Modelo.PersistenciaPregunta;
import Modelo.Pregunta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;
import java.util.TimerTask;
import java.util.ArrayList;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

public class VentanaCuestionario extends javax.swing.JFrame {

    int numero = 0;
    int seg = 31;
    int correcta = 0;
    int numPreguntas = 1;
    String respuesta;
    

    /**
     * Creates new form VentanaCuestionario
     */
    public VentanaCuestionario() {
        setAlwaysOnTop(true);
        initComponents();
        setSize(375, 459);
        setLocationRelativeTo(this);
        mostrarPregunta(numero++);

        Thread t1 = new Thread(new Runnable() {

            public void run() {

                while (true) {
                    seg--;

                    try {
                        Thread.sleep(1000);
                        etiquetaTiempo.setText("Tiempo: " + seg);
                        if (seg == 0) {
                            mostrarPregunta(numero++);
                            numPreguntas++;
                            jLabel2.setText(numero + " de 8");
                            
                            if (numPreguntas > 8) {
                                JOptionPane.showMessageDialog(null, "Resultado: " + correcta);
                            }
                        }

                    } catch (Exception ex) {

                    }
                }
            }
        });
        t1.start();

        
        rb1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String texto = rb1.getText();
                if (rb1.isSelected()) {
                    texto = "" + texto;
                    jLCorrecta.setText(texto);
                }

            }
        });

        rb2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String texto = rb2.getText();
                if (rb2.isSelected()) {
                    texto = "" + texto;
                    jLCorrecta.setText(texto);
                }

            }
        });

        rb3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String texto = rb3.getText();
                if (rb3.isSelected()) {
                    texto = "" + texto;
                    jLCorrecta.setText(texto);
                }

            }
        });

        rb4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String texto = rb4.getText();
                if (rb4.isSelected()) {
                    texto = "" + texto;
                    jLCorrecta.setText(texto);
                }
            }
        });

    }

    public void mostrarPregunta(int numero) {
        seg = 30;
        try {
            //Primero sacamosla pregunta del numero dado
            ArrayList<Pregunta> preguntas = PersistenciaPregunta.leer();
            Pregunta p = preguntas.get(numero);
            //Ajustamos los valores
            //Primero va el titulo
            etiquetaPregunta.setText(p.getTitulo());
            //Ahora las opciones
            ArrayList<Opcion> opciones = p.getOpciones();
            respuesta = opciones.get(0).getTitulo();
            JLResultado.setText(respuesta);
            //Aplicamos el algoritmo
            opciones = PersistenciaPregunta.opcionesAleatorias(opciones);
            rb1.setText(opciones.get(0).getTitulo());
            rb2.setText(opciones.get(1).getTitulo());
            rb3.setText(opciones.get(2).getTitulo());
            rb4.setText(opciones.get(3).getTitulo());
        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        etiquetaTiempo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiquetaPregunta = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLCorrecta = new javax.swing.JLabel();
        JLResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        etiquetaTiempo.setText("Tiemp: 30");
        getContentPane().add(etiquetaTiempo);
        etiquetaTiempo.setBounds(80, 40, 120, 14);

        jLabel2.setText("1 de 8");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 120, 60, 14);

        etiquetaPregunta.setText("Aqui va a ir la pregunta");
        getContentPane().add(etiquetaPregunta);
        etiquetaPregunta.setBounds(80, 140, 270, 20);

        buttonGroup1.add(rb1);
        rb1.setText("jRadioButton1");
        getContentPane().add(rb1);
        rb1.setBounds(140, 170, 190, 23);

        buttonGroup1.add(rb2);
        rb2.setText("jRadioButton2");
        getContentPane().add(rb2);
        rb2.setBounds(140, 190, 190, 23);

        buttonGroup1.add(rb3);
        rb3.setText("jRadioButton3");
        getContentPane().add(rb3);
        rb3.setBounds(140, 220, 190, 23);

        buttonGroup1.add(rb4);
        rb4.setText("jRadioButton4");
        getContentPane().add(rb4);
        rb4.setBounds(140, 240, 190, 23);

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 270, 49, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-\\Documents\\NetBeansProjects\\objetos-1803\\Proyecto\\src\\Vista\\pln.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 370, 450);

        jLCorrecta.setText("jLabel3");
        getContentPane().add(jLCorrecta);
        jLCorrecta.setBounds(50, 340, 34, 14);

        JLResultado.setText("jLabel3");
        getContentPane().add(JLResultado);
        JLResultado.setBounds(250, 330, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        numPreguntas++;
        jLabel2.setText(numPreguntas + " de 8");
        if (jLCorrecta.getText().equals(JLResultado.getText())) {
            correcta++;
        }

        if (numPreguntas > 8) {
            dispose();
            JOptionPane.showMessageDialog(null, "Resultado: " + correcta);
        }
        mostrarPregunta(numero++);
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLResultado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etiquetaPregunta;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLCorrecta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    // End of variables declaration//GEN-END:variables

    private JLabel Temporizador() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
